const GEO_QUIZ = [
  {
    section: "Natural Hazards",
    topics: [
      {
        topic: "Tectonic Hazards",
        questions: [
          {
            q: "Explain why earthquakes occur at convergent plate boundaries.",
            markScheme: [
              "Density differences cause oceanic plates to subduct",
              "Friction prevents smooth movement",
              "Stress builds up over time",
              "Sudden release of stress causes earthquake"
            ],
            maxMarks: 4,
            keywords: ["density", "subduct", "friction", "stress", "release"],
            modelAnswer: "At convergent boundaries, denser oceanic plates are forced beneath lighter continental plates (subduction). Friction prevents smooth movement, so stress accumulates. When the stress exceeds the friction force, the plates suddenly slip, releasing energy as an earthquake.",
            hint: "Think about how plates collide and what builds up between them."
          },
          {
            q: "Describe two ways that volcanic eruptions can be hazardous to people.",
            markScheme: [
              "Lava flows destroy buildings and farmland",
              "Pyroclastic flows move rapidly and burn everything",
              "Ash clouds reduce visibility and damage lungs",
              "Lahars (mudflows) bury settlements"
            ],
            maxMarks: 4,
            keywords: ["lava", "pyroclastic", "ash", "lahar", "destroy", "damage"],
            modelAnswer: "Lava flows from the volcano destroy buildings and agricultural land in their path. Pyroclastic flows—superheated gas and rock moving at high speed—can incinerate entire settlements. Volcanic ash clouds reduce visibility, damage engines, and cause respiratory problems.",
            hint: "Consider direct hazards from the volcano and secondary effects."
          },
          {
            q: "Explain how the Boxing Day tsunami (2004) was generated by an earthquake.",
            markScheme: [
              "Megathrust earthquake at subduction zone (9.0-9.3 magnitude)",
              "Sudden uplift of seafloor displaced huge volume of water",
              "Water displaced created waves radiating outward",
              "Waves travelled at ~800 km/h across ocean"
            ],
            maxMarks: 4,
            keywords: ["megathrust", "subduction", "uplift", "seafloor", "displacement", "magnitude"],
            modelAnswer: "A magnitude 9.0-9.3 megathrust earthquake occurred at the Sumatra-Andaman subduction zone. The sudden vertical uplift of the seafloor displaced an enormous volume of water, creating tsunami waves. These waves radiated outward at ~800 km/h and struck coastlines across the Indian Ocean.",
            hint: "Focus on the specific type of earthquake and how it moved the ocean."
          }
        ]
      },
      {
        topic: "Weather Hazards",
        questions: [
          {
            q: "Explain why tropical cyclones form over warm ocean waters.",
            markScheme: [
              "Water temperature >26.5°C provides energy",
              "Warm air rises creating low pressure",
              "Water evaporates, releasing latent heat",
              "Coriolis force causes rotation"
            ],
            maxMarks: 4,
            keywords: ["warm", "26.5", "evaporate", "latent heat", "low pressure", "Coriolis"],
            modelAnswer: "Tropical cyclones form over oceans where water temperature exceeds 26.5°C. This warmth causes water to evaporate and warm air to rise, creating a low-pressure system. The latent heat released during evaporation provides energy for the system. The Coriolis force causes the rising air to rotate.",
            hint: "Think about heat energy and how it drives the system."
          },
          {
            q: "Describe the structure of a tropical cyclone.",
            markScheme: [
              "Eye: calm centre with light winds",
              "Eye wall: band of intense thunderstorms surrounding eye",
              "Rainbands: spiral rain clouds extending outward",
              "Wind speeds decrease towards the edge"
            ],
            maxMarks: 4,
            keywords: ["eye", "calm", "eye wall", "thunderstorms", "rainbands", "spiral"],
            modelAnswer: "A tropical cyclone has a circular structure. At the centre is the eye—a calm area with light winds. Surrounding the eye is the eye wall, a band of intense thunderstorms with the strongest winds. Spiral rainbands extend outward from the eye wall, with wind speeds gradually decreasing towards the edge.",
            hint: "Describe from the centre outward."
          }
        ]
      }
    ]
  },
  {
    section: "Physical Landscapes",
    topics: [
      {
        topic: "Coastal Processes",
        questions: [
          {
            q: "Explain how longshore drift transports sediment along a coastline.",
            markScheme: [
              "Waves approach at an angle to the shore",
              "Swash carries sediment up the beach at that angle",
              "Backwash pulls sediment straight back down",
              "Net effect moves sediment along the shore"
            ],
            maxMarks: 4,
            keywords: ["angle", "swash", "backwash", "sediment", "transport"],
            modelAnswer: "Waves approach the shore at an angle rather than straight on. The swash (incoming wave) carries sediment up the beach in the direction the wave is traveling. The backwash (retreating water) pulls the sediment straight back down due to gravity. This zigzag motion results in net movement of sediment along the shore.",
            hint: "Consider what happens during each part of a wave cycle."
          },
          {
            q: "Compare erosional and depositional landforms at the coast.",
            markScheme: [
              "Erosional: cliffs, wave-cut platforms, headlands from wave attack",
              "Depositional: beaches, spits, bars from sediment accumulation",
              "Erosional form where high-energy waves remove material",
              "Depositional form where low-energy conditions allow sediment settling"
            ],
            maxMarks: 4,
            keywords: ["erosional", "depositional", "cliffs", "platforms", "beaches", "spits", "high-energy", "low-energy"],
            modelAnswer: "Erosional landforms like cliffs and wave-cut platforms form where high-energy waves attack the shore, removing material. Depositional landforms like beaches and spits form in low-energy areas where waves have insufficient energy to remove sediment, allowing it to accumulate.",
            hint: "Think about where waves are strong versus weak."
          }
        ]
      },
      {
        topic: "River Processes",
        questions: [
          {
            q: "Explain how a river erodes its channel through the processes of hydraulic action and abrasion.",
            markScheme: [
              "Hydraulic action: force of water under pressure breaks rock",
              "Abrasion: sediment in water acts like sandpaper, scraping the channel",
              "Both processes remove material from river bed and banks",
              "Combined effect deepens and widens the channel"
            ],
            maxMarks: 4,
            keywords: ["hydraulic action", "pressure", "abrasion", "sediment", "sandpaper", "scraping"],
            modelAnswer: "Hydraulic action occurs when the force of water under pressure breaks and loosens rock material from the riverbed and banks. Abrasion happens when sediment particles carried by the river act like sandpaper, scraping and smoothing the channel. Together, these erosional processes remove material and gradually deepen and widen the river channel.",
            hint: "Describe two different ways water/sediment removes rock."
          }
        ]
      }
    ]
  },
  {
    section: "Human Geography",
    topics: [
      {
        topic: "Urban Development",
        questions: [
          {
            q: "Explain why rapid urbanization in developing countries can cause problems.",
            markScheme: [
              "Rural-urban migration exceeds housing supply",
              "Slums/shanty towns develop with poor sanitation",
              "Infrastructure (water, sewerage) inadequate",
              "High unemployment and poverty in urban areas"
            ],
            maxMarks: 4,
            keywords: ["migration", "housing", "slums", "shanty", "infrastructure", "sanitation"],
            modelAnswer: "Rapid urbanization occurs when rural-urban migration exceeds the rate of housing construction. This creates slums and shanty towns with poor sanitation. Infrastructure such as water supply, sewerage, and electricity cannot keep pace with the growing population. High unemployment and poverty persist as not enough jobs are created.",
            hint: "Think about what happens when people move to cities faster than the city can accommodate them."
          },
          {
            q: "Describe the characteristics of a Megacity.",
            markScheme: [
              "Population exceeds 10 million people",
              "Dominates its country's economy and politics",
              "Has significant global influence and connectivity",
              "Complex diverse economic base with varied employment"
            ],
            maxMarks: 4,
            keywords: ["10 million", "dominates", "economy", "politics", "global", "influence"],
            modelAnswer: "A megacity has a population exceeding 10 million people. It dominates its country's economy and political system. Megacities have significant global influence through finance, culture, and trade. They have complex, diverse economies with varied employment opportunities across services, manufacturing, and finance sectors.",
            hint: "Focus on size, influence, and economic importance."
          }
        ]
      },
      {
        topic: "Development & Inequality",
        questions: [
          {
            q: "Explain what is meant by sustainable development.",
            markScheme: [
              "Meeting the needs of the present generation",
              "Without compromising needs of future generations",
              "Balancing economic, social, and environmental factors",
              "Conservation of resources for long-term use"
            ],
            maxMarks: 4,
            keywords: ["present", "future", "needs", "economic", "social", "environmental", "conservation"],
            modelAnswer: "Sustainable development means meeting the needs of present generations while ensuring that future generations can also meet their needs. It requires balancing economic development, social well-being, and environmental protection. Resources must be used in a way that allows for long-term conservation and availability.",
            hint: "Think about balancing today's needs with tomorrow's."
          }
        ]
      }
    ]
  }
];
